apiVersion: platform.taskapp.io/v1alpha1
kind: ApplicationRepository
metadata:
  labels:
    app.kubernetes.io/name: application-repository-operator
    app.kubernetes.io/managed-by: kustomize
  name: applicationrepository-sample
spec:
  repoURL: https://github.com/entr0pian/example.git
  targetRevision: main
  chartPath: chart
  clusters:
    - name: dev
      namespace: default
